-- If not using docker, create the db on the postgres service-db, then reopen the connection to the actual db
-- CREATE DATABASE "WerewolfCircle";

-- The project uses EF migrations. The db-script was generated with the help of the `dotnet-ef` tool.

CREATE TABLE "Games" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoomId" text NOT NULL,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id")
);

CREATE TABLE "Players" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "GameId" integer NOT NULL,
    CONSTRAINT "PK_Players" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Players_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Games_RoomId" ON "Games" ("RoomId");

CREATE INDEX "IX_Players_GameId" ON "Players" ("GameId");
